# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
cinder_disk = './cinder-area.vdi' 

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|


  config.vm.define "openstack" do |openstack|
    openstack.vm.box = "keystone-moon-custom"
    #openstack.vm.box = "openstack"
    openstack.vm.network :private_network, ip: "192.168.62.10", virtualbox__intnet: "internal"
    openstack.vm.network :public_network
    openstack.vm.network :private_network, type: "dhcp"
    openstack.vm.network :forwarded_port, guest: 80, host: 8083
    openstack.vm.network :forwarded_port, guest: 443, host: 8453
    openstack.vm.network :forwarded_port, guest: 5000, host: 8084
    openstack.vm.network :forwarded_port, guest: 35357, host: 8085
    openstack.vm.network :forwarded_port, guest: 22, host: 22235
    openstack.vm.provider :virtualbox do |vb|
        #vb.customize ["modifyvm", :id, "--nictype1", "Am79C973"]
        #vb.customize ["modifyvm", :id, "--nictype2", "Am79C973"]
        #vb.customize ["modifyvm", :id, "--nictype3", "Am79C973"]
        vb.customize ["modifyvm", :id, "--memory", "4096"]
        vb.customize ["modifyvm", :id, "--cpus", "3"]
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
        unless File.exist?(cinder_disk)
            vb.customize ['createhd', '--filename', cinder_disk, '--size', 20 * 1024]
            vb.customize ['storageattach', :id, '--storagectl', 'SATAController', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', cinder_disk]
        end
    end
    #openstack.vm.provision "shell", inline: "touch /home/vagrant/.idp.lock"
  end

  config.vm.define "opendaylight" do |opendaylight|
    #opendaylight.vm.box = "opendaylight"
    opendaylight.vm.box = "beryllium-prebuild_2016-05-24"
    opendaylight.vm.network :private_network, ip: "192.168.62.30", virtualbox__intnet: "internal"
    opendaylight.vm.network :public_network
    opendaylight.vm.network :forwarded_port, guest: 80, host: 8180
    opendaylight.vm.network :forwarded_port, guest: 8181, host: 8181
    opendaylight.vm.network :forwarded_port, guest: 22, host: 22236
    opendaylight.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "4096"]
        vb.customize ["modifyvm", :id, "--cpus", "3"]
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end
    #opendaylight.vm.provision "shell", inline: "touch /home/vagrant/.sp.lock"
  end

    # All Vagrant configuration is done here. The most common configuration
    # options are documented and commented below. For a complete reference,
    # please see the online documentation at vagrantup.com.

    # Every Vagrant virtual environment requires a box to build off of.
    #config.vm.box = "ubuntu/trusty64"

    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    #config.vm.network :forwarded_port, guest: 80, host: 8073
    #config.vm.network :forwarded_port, guest: 5000, host: 8074
    #config.vm.network :forwarded_port, guest: 35357, host: 8075

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    #config.vm.network :private_network, ip: "192.168.33.30", virtualbox__intnet: "internal"

    # Create a public network, which generally matched to bridged network.
    # Bridged networks make the machine appear as another physical device on
    # your network.
    #config.vm.network :public_network

    # If true, then any SSH connections made will enable agent forwarding.
    # Default value: false
    # config.ssh.forward_agent = true

    # Share an additional folder to the guest VM. The first argument is
    # the path on the host to the actual folder. The second argument is
    # the path on the guest to mount the folder. And the optional third
    # argument is a set of non-required options.
    config.vm.boot_timeout=500
    # Provider-specific configuration so you can fine-tune various
    # backing providers for Vagrant. These expose provider-specific options.
    # Example for VirtualBox:
end
